version: "3.2"
services:

  developer:
    build:
        context: ../
        dockerfile: ./ci/Dockerfile
        args:          
          - USERID=1000
    image: syllogismrxs/cmake-project-template:developer
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /home/syllogismrxs/cmake-project-template
        read_only: false
